# Generated by Django 2.2 on 2019-09-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('urlDomain', models.CharField(max_length=30)),
                ('loadTime', models.IntegerField(default=0)),
                ('loadCode', models.IntegerField(default=0)),
                ('sizeB', models.IntegerField(default=0)),
            ],
        ),
    ]
