# Generated by Django 2.2 on 2019-09-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Stats',
        ),
    ]
