# Generated by Django 2.2 on 2019-09-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20190916_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='StatisticsUrl',
        ),
    ]
