# Generated by Django 2.2 on 2019-09-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20190917_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsurl',
            old_name='loadCode',
            new_name='status_code',
        ),
    ]
