# Generated by Django 2.2 on 2019-09-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20190917_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsurl',
            old_name='name',
            new_name='key_name',
        ),
    ]
