# Generated by Django 2.2 on 2019-09-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20190917_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsurl',
            old_name='sizeB',
            new_name='byte_size',
        ),
    ]
