# Generated by Django 2.2 on 2019-09-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20190917_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsurl',
            old_name='loadTime',
            new_name='load_time',
        ),
    ]
