# Generated by Django 2.2 on 2019-09-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20190917_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsurl',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='statisticsurl',
            old_name='urlDomain',
            new_name='url_domain',
        ),
    ]
